# Generated by Django 2.1 on 2020-04-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_name', models.CharField(max_length=200)),
                ('P_price', models.FloatField()),
                ('P_stock', models.IntegerField()),
                ('P_image_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
