# Generated by Django 2.1 on 2020-04-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('discount', models.FloatField()),
            ],
        ),
    ]
