# Generated by Django 3.0 on 2020-04-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=30)),
                ('number', models.IntegerField(default='', max_length=10)),
                ('password', models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='offer',
        ),
    ]
