# Generated by Django 3.0 on 2020-04-30 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_save_user_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userModel',
        ),
    ]
