# Generated by Django 3.0 on 2020-05-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('product', models.CharField(max_length=40)),
                ('item', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Save_user_data',
        ),
    ]
