# Generated by Django 3.0 on 2020-05-04 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200503_1411'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
