# Generated by Django 3.0 on 2020-05-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('product', models.CharField(max_length=40)),
                ('item', models.CharField(max_length=50)),
                ('item_url', models.CharField(max_length=2083)),
                ('item_price', models.CharField(max_length=50)),
            ],
        ),
    ]
