# Generated by Django 3.0 on 2020-05-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200504_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item_price',
            field=models.IntegerField(),
        ),
    ]
