# Generated by Django 3.0 on 2020-05-04 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200504_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='P_price',
        ),
    ]
