# Generated by Django 3.0 on 2020-05-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_product_p_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='P_price',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
