# Generated by Django 3.0 on 2020-05-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
