# Generated by Django 3.0 on 2020-05-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20200505_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill_amount',
            field=models.IntegerField(default=560),
            preserve_default=False,
        ),
    ]
