# Generated by Django 3.0 on 2020-05-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_order_bill_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.CharField(default=111, max_length=15),
            preserve_default=False,
        ),
    ]
